/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.david.jordan ;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Jordan
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelComboBox = new javax.swing.JPanel();
        jLabelChooseModule = new javax.swing.JLabel();
        jComboBoxModule = new javax.swing.JComboBox<>();
        jLabelModuleSelected = new javax.swing.JLabel();
        jPanelSpinner = new javax.swing.JPanel();
        jLabelChooseNumber = new javax.swing.JLabel();
        jSpinnerChooseNumber = new javax.swing.JSpinner();
        jLabelNumberSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComboBox and Spinner");

        jPanelMain.setBackground(new java.awt.Color(22, 74, 139));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("ComboBox and Spinner");

        jPanelComboBox.setBackground(new java.awt.Color(255, 237, 0));

        jLabelChooseModule.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelChooseModule.setForeground(new java.awt.Color(197, 32, 37));
        jLabelChooseModule.setLabelFor(jComboBoxModule);
        jLabelChooseModule.setText("ComboBox (Choose Module):");

        jComboBoxModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Computer Science", "2. Chemistr", "3. Drawing", "4. Economics", "5. English Language", "6. French Language", "7. History", "8. Maths", "9. Music", "10. Physical Education (PE)", "11. Physics", "12. Reinforcement", "13. Religion", "14. Science", "15. Social Science", "16. Spanish Language", "17. Technology" }));
        jComboBoxModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModuleActionPerformed(evt);
            }
        });

        jLabelModuleSelected.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModuleSelected.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModuleSelected.setText("Computer Science");

        javax.swing.GroupLayout jPanelComboBoxLayout = new javax.swing.GroupLayout(jPanelComboBox);
        jPanelComboBox.setLayout(jPanelComboBoxLayout);
        jPanelComboBoxLayout.setHorizontalGroup(
            jPanelComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComboBoxLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChooseModule))
                .addGap(18, 18, 18)
                .addComponent(jLabelModuleSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelComboBoxLayout.setVerticalGroup(
            jPanelComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComboBoxLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelChooseModule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModuleSelected))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelSpinner.setBackground(new java.awt.Color(255, 237, 0));

        jLabelChooseNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelChooseNumber.setForeground(new java.awt.Color(197, 32, 37));
        jLabelChooseNumber.setText("Spinner (Choose Number):");

        jSpinnerChooseNumber.setModel(new SpinnerNumberModel(5, 1, 10, 1));
        jSpinnerChooseNumber.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerChooseNumber, ""));
        jSpinnerChooseNumber.setPreferredSize(new java.awt.Dimension(175, 22));
        jSpinnerChooseNumber.setRequestFocusEnabled(false);
        jSpinnerChooseNumber.setValue(5);
        jSpinnerChooseNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerChooseNumberStateChanged(evt);
            }
        });

        jLabelNumberSelected.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNumberSelected.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumberSelected.setText("Number: 5");

        javax.swing.GroupLayout jPanelSpinnerLayout = new javax.swing.GroupLayout(jPanelSpinner);
        jPanelSpinner.setLayout(jPanelSpinnerLayout);
        jPanelSpinnerLayout.setHorizontalGroup(
            jPanelSpinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpinnerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelSpinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelChooseNumber)
                    .addGroup(jPanelSpinnerLayout.createSequentialGroup()
                        .addComponent(jSpinnerChooseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNumberSelected)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSpinnerLayout.setVerticalGroup(
            jPanelSpinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpinnerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelChooseNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSpinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerChooseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumberSelected))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabelTitle)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMainLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModuleActionPerformed
        // TODO add your handling code here:
        jLabelModuleSelected.setText(jComboBoxModule.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxModuleActionPerformed

    private void jSpinnerChooseNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerChooseNumberStateChanged
        // TODO add your handling code here:
        
        
                
       
       jLabelNumberSelected.setText("Number: " + jSpinnerChooseNumber.getValue().toString());
    }//GEN-LAST:event_jSpinnerChooseNumberStateChanged

    
    
//    private void jSpinnerModuleActionPerformed(){
//    
//        
//        String jLabelNumberSelectedText = jLabelNumberSelected.getText();
//        
//        jLabelChooseNumber.setText("Number: " + jLabelNumberSelectedText);
//        
//        
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxModule;
    private javax.swing.JLabel jLabelChooseModule;
    private javax.swing.JLabel jLabelChooseNumber;
    private javax.swing.JLabel jLabelModuleSelected;
    private javax.swing.JLabel jLabelNumberSelected;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelComboBox;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSpinner;
    private javax.swing.JSpinner jSpinnerChooseNumber;
    // End of variables declaration//GEN-END:variables
}
