/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tema2Formulario;

import java.awt.Color;

/**
 *
 * @author Jordan
 */
public class Form extends javax.swing.JDialog {

    static boolean controlColorProfession = true;

    /**
     * Creates new form Form
     */
    public Form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jOptionPane2 = new javax.swing.JOptionPane();
        jPanelMain = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelSection1_MainDates = new javax.swing.JPanel();
        jPanelCategory1_1_Profession = new javax.swing.JPanel();
        jLabel1_1_Profession = new javax.swing.JLabel();
        jTextField1_1_Profession = new javax.swing.JTextField();
        jPanelCategory1_2_Brothers = new javax.swing.JPanel();
        jLabel1_2_Brothers = new javax.swing.JLabel();
        jSpinner1_2_Brothers = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_2_Age = new javax.swing.JLabel();
        jComboBox1_2_Age = new javax.swing.JComboBox<>();
        jPanelCategory1_3_Sex = new javax.swing.JPanel();
        jPanel_buttonGroupCategory_1_3_Sex = new javax.swing.JPanel();
        jRadioButton1_3_Male = new javax.swing.JRadioButton();
        jRadioButton1_3_Female = new javax.swing.JRadioButton();
        jRadioButton1_3_Other = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelCategory1_4_Sport = new javax.swing.JPanel();
        jCheckBox1_4_Sport = new javax.swing.JCheckBox();
        jPanel1_4_WichSport = new javax.swing.JPanel();
        jLabel1_4_SelectSport = new javax.swing.JLabel();
        jScrollPane1_4_SelectSport = new javax.swing.JScrollPane();
        jList1_4_WhichSport = new javax.swing.JList<>();
        jSeparatorSection1_Section2 = new javax.swing.JSeparator();
        jPanelSection2_SatisfactionGrade = new javax.swing.JPanel();
        jPanelCategory2_1_Hobby = new javax.swing.JPanel();
        jLabel12_1_Hobby = new javax.swing.JLabel();
        jPanel2_1_Hobby = new javax.swing.JPanel();
        jLabel2_1_HobbyBuy = new javax.swing.JLabel();
        jSlider2_1_HobbyBuy = new javax.swing.JSlider();
        jLabel2_1_HobbyTV = new javax.swing.JLabel();
        jSlider2_1_HobbyTV = new javax.swing.JSlider();
        jLabel2_1_HobbyCine = new javax.swing.JLabel();
        jSlider2_1_HobbyCine = new javax.swing.JSlider();
        jPanelSection3_SendDates = new javax.swing.JPanel();
        jButton2_2_Acept = new javax.swing.JButton();
        jButton2_2_Cancel = new javax.swing.JButton();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setLocation(location());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 0));

        jPanelTitle.setBackground(new java.awt.Color(0, 0, 0));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("FORMULARIO");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitle)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelSection1_MainDates.setBackground(new java.awt.Color(214, 217, 224));
        jPanelSection1_MainDates.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos principales"));

        jLabel1_1_Profession.setLabelFor(jTextField1_1_Profession);
        jLabel1_1_Profession.setText("Profesión: ");

        jTextField1_1_Profession.setForeground(java.awt.Color.gray);
        jTextField1_1_Profession.setToolTipText("Escoger profesión");
        jTextField1_1_Profession.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_1_ProfessionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_1_ProfessionFocusLost(evt);
            }
        });
        jTextField1_1_Profession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_1_ProfessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCategory1_1_ProfessionLayout = new javax.swing.GroupLayout(jPanelCategory1_1_Profession);
        jPanelCategory1_1_Profession.setLayout(jPanelCategory1_1_ProfessionLayout);
        jPanelCategory1_1_ProfessionLayout.setHorizontalGroup(
            jPanelCategory1_1_ProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_1_ProfessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_1_Profession)
                .addGap(48, 48, 48)
                .addComponent(jTextField1_1_Profession)
                .addContainerGap())
        );
        jPanelCategory1_1_ProfessionLayout.setVerticalGroup(
            jPanelCategory1_1_ProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_1_ProfessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategory1_1_ProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_1_Profession)
                    .addComponent(jTextField1_1_Profession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1_2_Brothers.setLabelFor(jSpinner1_2_Brothers);
        jLabel1_2_Brothers.setText("Nº Hermanos");

        jSpinner1_2_Brothers.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1_2_Brothers.setToolTipText("Cantidad hermanos");

        javax.swing.GroupLayout jPanelCategory1_2_BrothersLayout = new javax.swing.GroupLayout(jPanelCategory1_2_Brothers);
        jPanelCategory1_2_Brothers.setLayout(jPanelCategory1_2_BrothersLayout);
        jPanelCategory1_2_BrothersLayout.setHorizontalGroup(
            jPanelCategory1_2_BrothersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_2_BrothersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_2_Brothers)
                .addGap(32, 32, 32)
                .addComponent(jSpinner1_2_Brothers)
                .addContainerGap())
        );
        jPanelCategory1_2_BrothersLayout.setVerticalGroup(
            jPanelCategory1_2_BrothersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_2_BrothersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategory1_2_BrothersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_2_Brothers)
                    .addComponent(jSpinner1_2_Brothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1_2_Age.setLabelFor(jComboBox1_2_Age);
        jLabel1_2_Age.setText("Edad: ");

        jComboBox1_2_Age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 18", "Entre 18 y 30", "Entre 30 y 50", "Entre 50 y 65", "Mayor de 65" }));
        jComboBox1_2_Age.setSelectedIndex(1);
        jComboBox1_2_Age.setToolTipText("Elección edad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_2_Age)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1_2_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_2_Age)
                    .addComponent(jComboBox1_2_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_buttonGroupCategory_1_3_Sex.setBackground(new java.awt.Color(212, 215, 222));
        jPanel_buttonGroupCategory_1_3_Sex.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        buttonGroupSex.add(jRadioButton1_3_Male);
        jRadioButton1_3_Male.setText("Hombre");
        jRadioButton1_3_Male.setToolTipText("Sexo - hombre");

        buttonGroupSex.add(jRadioButton1_3_Female);
        jRadioButton1_3_Female.setText("Mujer");
        jRadioButton1_3_Female.setToolTipText("Sexo - mujer");

        buttonGroupSex.add(jRadioButton1_3_Other);
        jRadioButton1_3_Other.setText("Otro");
        jRadioButton1_3_Other.setToolTipText("Sexo - otro");
        jRadioButton1_3_Other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_3_OtherActionPerformed(evt);
            }
        });

        buttonGroupSex.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Prefiero no decirlo");
        jRadioButton1.setToolTipText("Sexo - prefiero no decirlo");

        javax.swing.GroupLayout jPanel_buttonGroupCategory_1_3_SexLayout = new javax.swing.GroupLayout(jPanel_buttonGroupCategory_1_3_Sex);
        jPanel_buttonGroupCategory_1_3_Sex.setLayout(jPanel_buttonGroupCategory_1_3_SexLayout);
        jPanel_buttonGroupCategory_1_3_SexLayout.setHorizontalGroup(
            jPanel_buttonGroupCategory_1_3_SexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonGroupCategory_1_3_SexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1_3_Male)
                .addGap(79, 79, 79)
                .addComponent(jRadioButton1_3_Female)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1_3_Other)
                .addGap(73, 73, 73)
                .addComponent(jRadioButton1)
                .addContainerGap())
        );
        jPanel_buttonGroupCategory_1_3_SexLayout.setVerticalGroup(
            jPanel_buttonGroupCategory_1_3_SexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonGroupCategory_1_3_SexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buttonGroupCategory_1_3_SexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1_3_Male)
                    .addComponent(jRadioButton1_3_Female)
                    .addComponent(jRadioButton1_3_Other)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCategory1_3_SexLayout = new javax.swing.GroupLayout(jPanelCategory1_3_Sex);
        jPanelCategory1_3_Sex.setLayout(jPanelCategory1_3_SexLayout);
        jPanelCategory1_3_SexLayout.setHorizontalGroup(
            jPanelCategory1_3_SexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_3_SexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_buttonGroupCategory_1_3_Sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCategory1_3_SexLayout.setVerticalGroup(
            jPanelCategory1_3_SexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory1_3_SexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_buttonGroupCategory_1_3_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox1_4_Sport.setText("¿Practicas algún deporte?");
        jCheckBox1_4_Sport.setToolTipText("¿Practicas algún deporte?");
        jCheckBox1_4_Sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_4_SportActionPerformed(evt);
            }
        });

        jPanel1_4_WichSport.setEnabled(false);

        jLabel1_4_SelectSport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1_4_SelectSport.setText("¿Cuál?");
        jLabel1_4_SelectSport.setToolTipText("¿Cuál?");

        jList1_4_WhichSport.setBorder(null);
        jList1_4_WhichSport.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fútbol (Soccer)", "Baloncesto", "Tenis", "Golf", "Rugby", "Cricket", "Béisbol", "Boxeo", "Atletismo", "Natación" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1_4_WhichSport.setToolTipText("");
        jList1_4_WhichSport.setEnabled(false);
        jScrollPane1_4_SelectSport.setViewportView(jList1_4_WhichSport);

        javax.swing.GroupLayout jPanel1_4_WichSportLayout = new javax.swing.GroupLayout(jPanel1_4_WichSport);
        jPanel1_4_WichSport.setLayout(jPanel1_4_WichSportLayout);
        jPanel1_4_WichSportLayout.setHorizontalGroup(
            jPanel1_4_WichSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_4_WichSportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_4_SelectSport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1_4_SelectSport, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1_4_WichSportLayout.setVerticalGroup(
            jPanel1_4_WichSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_4_WichSportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1_4_SelectSport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1_4_WichSportLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1_4_SelectSport)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCategory1_4_SportLayout = new javax.swing.GroupLayout(jPanelCategory1_4_Sport);
        jPanelCategory1_4_Sport.setLayout(jPanelCategory1_4_SportLayout);
        jPanelCategory1_4_SportLayout.setHorizontalGroup(
            jPanelCategory1_4_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategory1_4_SportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1_4_Sport, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(172, 172, 172)
                .addComponent(jPanel1_4_WichSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCategory1_4_SportLayout.setVerticalGroup(
            jPanelCategory1_4_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategory1_4_SportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1_4_WichSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanelCategory1_4_SportLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jCheckBox1_4_Sport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSection1_MainDatesLayout = new javax.swing.GroupLayout(jPanelSection1_MainDates);
        jPanelSection1_MainDates.setLayout(jPanelSection1_MainDatesLayout);
        jPanelSection1_MainDatesLayout.setHorizontalGroup(
            jPanelSection1_MainDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection1_MainDatesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSection1_MainDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelCategory1_3_Sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCategory1_4_Sport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCategory1_2_Brothers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCategory1_1_Profession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelSection1_MainDatesLayout.setVerticalGroup(
            jPanelSection1_MainDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection1_MainDatesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCategory1_1_Profession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCategory1_2_Brothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCategory1_3_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCategory1_4_Sport, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jPanelSection2_SatisfactionGrade.setBackground(new java.awt.Color(214, 217, 224));

        jPanelCategory2_1_Hobby.setBorder(javax.swing.BorderFactory.createTitledBorder("Grado de satisfacción"));

        jLabel12_1_Hobby.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12_1_Hobby.setLabelFor(jPanel2_1_Hobby);
        jLabel12_1_Hobby.setText("Marque del 1 al 10 su grado de afición a:");
        jLabel12_1_Hobby.setToolTipText("Marque del 1 al 10 su grado de afición a:");

        jPanel2_1_Hobby.setBackground(new java.awt.Color(214, 217, 224));

        jLabel2_1_HobbyBuy.setLabelFor(jSlider2_1_HobbyBuy);
        jLabel2_1_HobbyBuy.setText("Compras");
        jLabel2_1_HobbyBuy.setToolTipText("Compras");

        jSlider2_1_HobbyBuy.setMajorTickSpacing(5);
        jSlider2_1_HobbyBuy.setMaximum(10);
        jSlider2_1_HobbyBuy.setMinorTickSpacing(1);
        jSlider2_1_HobbyBuy.setPaintLabels(true);
        jSlider2_1_HobbyBuy.setPaintTicks(true);
        jSlider2_1_HobbyBuy.setToolTipText("");
        jSlider2_1_HobbyBuy.setValue(5);

        jLabel2_1_HobbyTV.setLabelFor(jSlider2_1_HobbyTV);
        jLabel2_1_HobbyTV.setText("Televisión");
        jLabel2_1_HobbyTV.setToolTipText("Televisión");

        jSlider2_1_HobbyTV.setMajorTickSpacing(5);
        jSlider2_1_HobbyTV.setMaximum(10);
        jSlider2_1_HobbyTV.setMinorTickSpacing(1);
        jSlider2_1_HobbyTV.setPaintLabels(true);
        jSlider2_1_HobbyTV.setPaintTicks(true);
        jSlider2_1_HobbyTV.setToolTipText("");
        jSlider2_1_HobbyTV.setValue(5);

        jLabel2_1_HobbyCine.setLabelFor(jSlider2_1_HobbyCine);
        jLabel2_1_HobbyCine.setText("Cine");
        jLabel2_1_HobbyCine.setToolTipText("Cine");

        jSlider2_1_HobbyCine.setMajorTickSpacing(5);
        jSlider2_1_HobbyCine.setMaximum(10);
        jSlider2_1_HobbyCine.setMinorTickSpacing(1);
        jSlider2_1_HobbyCine.setPaintLabels(true);
        jSlider2_1_HobbyCine.setPaintTicks(true);
        jSlider2_1_HobbyCine.setToolTipText("");
        jSlider2_1_HobbyCine.setValue(5);

        javax.swing.GroupLayout jPanel2_1_HobbyLayout = new javax.swing.GroupLayout(jPanel2_1_Hobby);
        jPanel2_1_Hobby.setLayout(jPanel2_1_HobbyLayout);
        jPanel2_1_HobbyLayout.setHorizontalGroup(
            jPanel2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_1_HobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider2_1_HobbyBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2_1_HobbyLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_1_HobbyCine)
                            .addComponent(jLabel2_1_HobbyTV)
                            .addComponent(jLabel2_1_HobbyBuy))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSlider2_1_HobbyTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider2_1_HobbyCine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2_1_HobbyLayout.setVerticalGroup(
            jPanel2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_1_HobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2_1_HobbyBuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider2_1_HobbyBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2_1_HobbyTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider2_1_HobbyTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2_1_HobbyCine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider2_1_HobbyCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCategory2_1_HobbyLayout = new javax.swing.GroupLayout(jPanelCategory2_1_Hobby);
        jPanelCategory2_1_Hobby.setLayout(jPanelCategory2_1_HobbyLayout);
        jPanelCategory2_1_HobbyLayout.setHorizontalGroup(
            jPanelCategory2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategory2_1_HobbyLayout.createSequentialGroup()
                .addGap(0, 172, Short.MAX_VALUE)
                .addComponent(jLabel12_1_Hobby)
                .addGap(145, 145, 145))
            .addGroup(jPanelCategory2_1_HobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2_1_Hobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCategory2_1_HobbyLayout.setVerticalGroup(
            jPanelCategory2_1_HobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategory2_1_HobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12_1_Hobby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2_1_Hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSection2_SatisfactionGradeLayout = new javax.swing.GroupLayout(jPanelSection2_SatisfactionGrade);
        jPanelSection2_SatisfactionGrade.setLayout(jPanelSection2_SatisfactionGradeLayout);
        jPanelSection2_SatisfactionGradeLayout.setHorizontalGroup(
            jPanelSection2_SatisfactionGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection2_SatisfactionGradeLayout.createSequentialGroup()
                .addComponent(jPanelCategory2_1_Hobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSection2_SatisfactionGradeLayout.setVerticalGroup(
            jPanelSection2_SatisfactionGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection2_SatisfactionGradeLayout.createSequentialGroup()
                .addComponent(jPanelCategory2_1_Hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2_2_Acept.setText("Aceptar");
        jButton2_2_Acept.setToolTipText("Botón Cancelar");
        jButton2_2_Acept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_2_AceptActionPerformed(evt);
            }
        });

        jButton2_2_Cancel.setText("Cancelar");
        jButton2_2_Cancel.setToolTipText("Botón Aceptar");
        jButton2_2_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_2_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSection3_SendDatesLayout = new javax.swing.GroupLayout(jPanelSection3_SendDates);
        jPanelSection3_SendDates.setLayout(jPanelSection3_SendDatesLayout);
        jPanelSection3_SendDatesLayout.setHorizontalGroup(
            jPanelSection3_SendDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection3_SendDatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2_2_Acept, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_2_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
        jPanelSection3_SendDatesLayout.setVerticalGroup(
            jPanelSection3_SendDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSection3_SendDatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSection3_SendDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2_2_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jButton2_2_Acept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanelSection1_MainDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparatorSection1_Section2))
                .addContainerGap())
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanelMainLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSection3_SendDates, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSection2_SatisfactionGrade, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSection1_MainDates, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparatorSection1_Section2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSection2_SatisfactionGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSection3_SendDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1_4_SportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_4_SportActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1_4_Sport.isSelected()) {
            jList1_4_WhichSport.setEnabled(true);
        } else {
            jList1_4_WhichSport.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1_4_SportActionPerformed

    private void jButton2_2_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_2_CancelActionPerformed
        // TODO add your handling code here:
        ModalCancelarAceptar.ModalCancelar(this);


    }//GEN-LAST:event_jButton2_2_CancelActionPerformed

    private void jTextField1_1_ProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_1_ProfessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_1_ProfessionActionPerformed

    private void jButton2_2_AceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_2_AceptActionPerformed
        // TODO add your handling code here:
        if (!controlColorProfession) {
            ModalCancelarAceptar.ModalAceptarIncorrecto(this);
            jTextField1_1_Profession.setBackground(Color.red);
        } else {
            ModalCancelarAceptar.ModalAceptarCorrecto(this);
        }
        
    }//GEN-LAST:event_jButton2_2_AceptActionPerformed

    private void jRadioButton1_3_OtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_3_OtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1_3_OtherActionPerformed

    private void jTextField1_1_ProfessionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_1_ProfessionFocusGained
        // TODO add your handling code here:

        if (jTextField1_1_Profession.getText().equals("Escoja profesión")) {
            jTextField1_1_Profession.setText("");
            jTextField1_1_Profession.setForeground(Color.black);
            jTextField1_1_Profession.setBackground(Color.white);
            controlColorProfession = true;
        }
    }//GEN-LAST:event_jTextField1_1_ProfessionFocusGained

    private void jTextField1_1_ProfessionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_1_ProfessionFocusLost
        // TODO add your handling code here:
        if (jTextField1_1_Profession.getText().equals("")) {
            jTextField1_1_Profession.setText("Escoja profesión");
            jTextField1_1_Profession.setForeground(Color.gray);
            controlColorProfession = false;
        }
    }//GEN-LAST:event_jTextField1_1_ProfessionFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form dialog = new Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.JButton jButton2_2_Acept;
    private javax.swing.JButton jButton2_2_Cancel;
    private javax.swing.JCheckBox jCheckBox1_4_Sport;
    private javax.swing.JComboBox<String> jComboBox1_2_Age;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel12_1_Hobby;
    private javax.swing.JLabel jLabel1_1_Profession;
    private javax.swing.JLabel jLabel1_2_Age;
    private javax.swing.JLabel jLabel1_2_Brothers;
    private javax.swing.JLabel jLabel1_4_SelectSport;
    private javax.swing.JLabel jLabel2_1_HobbyBuy;
    private javax.swing.JLabel jLabel2_1_HobbyCine;
    private javax.swing.JLabel jLabel2_1_HobbyTV;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jList1_4_WhichSport;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_4_WichSport;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_1_Hobby;
    private javax.swing.JPanel jPanelCategory1_1_Profession;
    private javax.swing.JPanel jPanelCategory1_2_Brothers;
    private javax.swing.JPanel jPanelCategory1_3_Sex;
    private javax.swing.JPanel jPanelCategory1_4_Sport;
    private javax.swing.JPanel jPanelCategory2_1_Hobby;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSection1_MainDates;
    private javax.swing.JPanel jPanelSection2_SatisfactionGrade;
    private javax.swing.JPanel jPanelSection3_SendDates;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanel_buttonGroupCategory_1_3_Sex;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1_3_Female;
    private javax.swing.JRadioButton jRadioButton1_3_Male;
    private javax.swing.JRadioButton jRadioButton1_3_Other;
    private javax.swing.JScrollPane jScrollPane1_4_SelectSport;
    private javax.swing.JSeparator jSeparatorSection1_Section2;
    private javax.swing.JSlider jSlider2_1_HobbyBuy;
    private javax.swing.JSlider jSlider2_1_HobbyCine;
    private javax.swing.JSlider jSlider2_1_HobbyTV;
    private javax.swing.JSpinner jSpinner1_2_Brothers;
    private javax.swing.JTextField jTextField1_1_Profession;
    // End of variables declaration//GEN-END:variables
}
