/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tema2SalonHabana;

import Tema2SalonHabana.dto.Reserve;
import com.toedter.calendar.JYearChooser;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Jordan
 */
public class GestionReservaSalonHabana extends javax.swing.JDialog {

    final static Color BACKGROUND_BLACK_SOFT = new Color(78, 79, 86);
    final static Color BORDER_BLACK_SOFT = new Color(122, 138, 153);
    final static Color WHITE = new Color(255, 255, 255);
    final static Color BLACK = new Color(0, 0, 0);
    final static Color RED = new Color(255, 0, 0);

    static boolean controlDatesCorrect = true;

    String name;
    String phone;
    String numPersons;
    Date selectedDate;
    String cousine;
    String event;

    Reserve reserve;
    AdministracionSalonHabana salonHabana;

    /**
     * Creates new form GestionReservaSalonHabana
     */
    public GestionReservaSalonHabana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        salonHabana = (AdministracionSalonHabana) parent;
        initComponents();
        initComponentsPersonalDates();
        initComponentsCalendar();
        initComponentNumberPersons();
        initComponentTypeCuisine();
        initComponentTypeEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelSection1_ClientDates = new javax.swing.JPanel();
        jPanelClientDatesBackground = new javax.swing.JPanel();
        jPanelClientName = new javax.swing.JPanel();
        jLabel1_1_ClientName = new javax.swing.JLabel();
        jTextField1_1_ClientName = new javax.swing.JTextField();
        jPanelClientPhone = new javax.swing.JPanel();
        jLabel1_2_ClientPhone = new javax.swing.JLabel();
        jTextField1_2_ClientPhone = new javax.swing.JTextField();
        jPanelSection2_HallDates = new javax.swing.JPanel();
        jPanelNumberPersons = new javax.swing.JPanel();
        jLabelNumberPersons = new javax.swing.JLabel();
        jCheckBoxNumberPersonsOther = new javax.swing.JCheckBox();
        jPanelNumberPersonsChoose = new javax.swing.JPanel();
        jButtonNumberPersonsOne = new javax.swing.JButton();
        jButtonNumberPersonsTwo = new javax.swing.JButton();
        jButtonNumberPersonsThree = new javax.swing.JButton();
        jButtonNumberPersonsFour = new javax.swing.JButton();
        jButtonNumberPersonsFive = new javax.swing.JButton();
        jButtonNumberPersonsSix = new javax.swing.JButton();
        jButtonNumberPersonsSeven = new javax.swing.JButton();
        jButtonNumberPersonsEight = new javax.swing.JButton();
        jSpinnerNumberPersonsOther = new javax.swing.JSpinner();
        jPanelExtraHallDates = new javax.swing.JPanel();
        jPanelDate = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        jCalendarDate = new com.toedter.calendar.JCalendar();
        jLabelDateChoosen = new javax.swing.JLabel();
        jPanelHallType = new javax.swing.JPanel();
        jPanelCuisine = new javax.swing.JPanel();
        jLabelCuisine = new javax.swing.JLabel();
        jButtonBuffet = new javax.swing.JButton();
        jButtonCard = new javax.swing.JButton();
        jButtonChef = new javax.swing.JButton();
        jButtonOwnChoose = new javax.swing.JButton();
        jPanelEvent = new javax.swing.JPanel();
        jLabelEvent = new javax.swing.JLabel();
        jButtonFeast = new javax.swing.JButton();
        jButtonDayWork = new javax.swing.JButton();
        jButtonCongress = new javax.swing.JButton();
        jPanelRoom = new javax.swing.JPanel();
        jLabelRoom = new javax.swing.JLabel();
        jButtonRoomNo = new javax.swing.JButton();
        jButtonRoomYes = new javax.swing.JButton();
        jPanelRoomsDays = new javax.swing.JPanel();
        jLabelRoomDays = new javax.swing.JLabel();
        jSpinnerRoomDays = new javax.swing.JSpinner();
        jButtonReserve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de reserva");
        setLocation(new java.awt.Point(200, 0));
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(234, 247, 255));

        jPanelTitle.setBackground(new java.awt.Color(11, 12, 99));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("DATOS DE RESERVA");
        jLabelTitle.setToolTipText("Datos de reserva");
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanelSection1_ClientDates.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSection1_ClientDates.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos cliente"));

        jPanelClientName.setOpaque(false);
        jPanelClientName.setPreferredSize(new java.awt.Dimension(590, 42));

        jLabel1_1_ClientName.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1_1_ClientName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/signature_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1_1_ClientName.setLabelFor(jTextField1_1_ClientName);
        jLabel1_1_ClientName.setText("Nombre:");
        jLabel1_1_ClientName.setToolTipText("Nombre");

        jTextField1_1_ClientName.setForeground(java.awt.Color.gray);
        jTextField1_1_ClientName.setToolTipText("Campo texto nombre");
        jTextField1_1_ClientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1_1_ClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_1_ClientNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientNameLayout = new javax.swing.GroupLayout(jPanelClientName);
        jPanelClientName.setLayout(jPanelClientNameLayout);
        jPanelClientNameLayout.setHorizontalGroup(
            jPanelClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_1_ClientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1_1_ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelClientNameLayout.setVerticalGroup(
            jPanelClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_1_ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_1_ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelClientPhone.setOpaque(false);
        jPanelClientPhone.setPreferredSize(new java.awt.Dimension(590, 42));

        jLabel1_2_ClientPhone.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1_2_ClientPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/smartphone_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1_2_ClientPhone.setLabelFor(jTextField1_2_ClientPhone);
        jLabel1_2_ClientPhone.setText("Teléfono:");
        jLabel1_2_ClientPhone.setToolTipText("Teléfono");

        jTextField1_2_ClientPhone.setForeground(java.awt.Color.gray);
        jTextField1_2_ClientPhone.setToolTipText("Campo texto teléfono");
        jTextField1_2_ClientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_2_ClientPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientPhoneLayout = new javax.swing.GroupLayout(jPanelClientPhone);
        jPanelClientPhone.setLayout(jPanelClientPhoneLayout);
        jPanelClientPhoneLayout.setHorizontalGroup(
            jPanelClientPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_2_ClientPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jTextField1_2_ClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelClientPhoneLayout.setVerticalGroup(
            jPanelClientPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_2_ClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_2_ClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelClientDatesBackgroundLayout = new javax.swing.GroupLayout(jPanelClientDatesBackground);
        jPanelClientDatesBackground.setLayout(jPanelClientDatesBackgroundLayout);
        jPanelClientDatesBackgroundLayout.setHorizontalGroup(
            jPanelClientDatesBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientDatesBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelClientDatesBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelClientName, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addComponent(jPanelClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelClientDatesBackgroundLayout.setVerticalGroup(
            jPanelClientDatesBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientDatesBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelSection1_ClientDatesLayout = new javax.swing.GroupLayout(jPanelSection1_ClientDates);
        jPanelSection1_ClientDates.setLayout(jPanelSection1_ClientDatesLayout);
        jPanelSection1_ClientDatesLayout.setHorizontalGroup(
            jPanelSection1_ClientDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection1_ClientDatesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanelClientDatesBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSection1_ClientDatesLayout.setVerticalGroup(
            jPanelSection1_ClientDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection1_ClientDatesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelClientDatesBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanelSection2_HallDates.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSection2_HallDates.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del salón"));

        jPanelNumberPersons.setBackground(new java.awt.Color(204, 204, 204));
        jPanelNumberPersons.setOpaque(false);

        jLabelNumberPersons.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelNumberPersons.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumberPersons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/group_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabelNumberPersons.setText("Número de personas:");
        jLabelNumberPersons.setToolTipText("Número de personas");

        jCheckBoxNumberPersonsOther.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxNumberPersonsOther.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jCheckBoxNumberPersonsOther.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxNumberPersonsOther.setText("Otra cantidad");
        jCheckBoxNumberPersonsOther.setToolTipText("Check more people");
        jCheckBoxNumberPersonsOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNumberPersonsOtherActionPerformed(evt);
            }
        });

        jPanelNumberPersonsChoose.setBackground(new java.awt.Color(248, 248, 248));
        jPanelNumberPersonsChoose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonNumberPersonsOne.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsOne.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsOne.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsOne.setText("1");
        jButtonNumberPersonsOne.setToolTipText("1 person");
        jButtonNumberPersonsOne.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNumberPersonsOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberPersonsOneActionPerformed(evt);
            }
        });

        jButtonNumberPersonsTwo.setBackground(new java.awt.Color(78, 79, 86));
        jButtonNumberPersonsTwo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsTwo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsTwo.setText("2");
        jButtonNumberPersonsTwo.setToolTipText("2 persons");
        jButtonNumberPersonsTwo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsThree.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsThree.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsThree.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsThree.setText("3");
        jButtonNumberPersonsThree.setToolTipText("3 persons");
        jButtonNumberPersonsThree.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsFour.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsFour.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsFour.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsFour.setText("4");
        jButtonNumberPersonsFour.setToolTipText("4 persons");
        jButtonNumberPersonsFour.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsFive.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsFive.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsFive.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsFive.setText("5");
        jButtonNumberPersonsFive.setToolTipText("5 persons");
        jButtonNumberPersonsFive.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsSix.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsSix.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsSix.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsSix.setText("6");
        jButtonNumberPersonsSix.setToolTipText("6 persons");
        jButtonNumberPersonsSix.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsSeven.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsSeven.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsSeven.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsSeven.setText("7");
        jButtonNumberPersonsSeven.setToolTipText("7 persons");
        jButtonNumberPersonsSeven.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNumberPersonsEight.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNumberPersonsEight.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonNumberPersonsEight.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNumberPersonsEight.setText("8");
        jButtonNumberPersonsEight.setToolTipText("8 persons");
        jButtonNumberPersonsEight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNumberPersonsEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberPersonsEightActionPerformed(evt);
            }
        });

        jSpinnerNumberPersonsOther.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jSpinnerNumberPersonsOther.setModel(new javax.swing.SpinnerNumberModel(9, 9, null, 1));
        jSpinnerNumberPersonsOther.setToolTipText("Selector más gente");
        jSpinnerNumberPersonsOther.setEnabled(false);
        jSpinnerNumberPersonsOther.setOpaque(true);

        javax.swing.GroupLayout jPanelNumberPersonsChooseLayout = new javax.swing.GroupLayout(jPanelNumberPersonsChoose);
        jPanelNumberPersonsChoose.setLayout(jPanelNumberPersonsChooseLayout);
        jPanelNumberPersonsChooseLayout.setHorizontalGroup(
            jPanelNumberPersonsChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumberPersonsChooseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNumberPersonsOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNumberPersonsEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSpinnerNumberPersonsOther)
                .addContainerGap())
        );
        jPanelNumberPersonsChooseLayout.setVerticalGroup(
            jPanelNumberPersonsChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumberPersonsChooseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumberPersonsChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumberPersonsOne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsThree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsFour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsFive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsSix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNumberPersonsOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberPersonsEight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNumberPersonsLayout = new javax.swing.GroupLayout(jPanelNumberPersons);
        jPanelNumberPersons.setLayout(jPanelNumberPersonsLayout);
        jPanelNumberPersonsLayout.setHorizontalGroup(
            jPanelNumberPersonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumberPersonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelNumberPersonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNumberPersonsChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNumberPersonsLayout.createSequentialGroup()
                        .addComponent(jLabelNumberPersons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxNumberPersonsOther)))
                .addContainerGap())
        );
        jPanelNumberPersonsLayout.setVerticalGroup(
            jPanelNumberPersonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumberPersonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelNumberPersonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumberPersons)
                    .addComponent(jCheckBoxNumberPersonsOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNumberPersonsChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), null));

        jLabelDate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/calendar_month_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabelDate.setText("Seleccionar una fecha");

        jLabelDateChoosen.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelDateChoosen.setText("(Fecha)");
        jLabelDateChoosen.setToolTipText("Fecha escogida");

        javax.swing.GroupLayout jPanelDateLayout = new javax.swing.GroupLayout(jPanelDate);
        jPanelDate.setLayout(jPanelDateLayout);
        jPanelDateLayout.setHorizontalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDateLayout.createSequentialGroup()
                        .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDateLayout.createSequentialGroup()
                        .addComponent(jLabelDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDateChoosen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDateLayout.setVerticalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDate)
                    .addComponent(jLabelDateChoosen))
                .addGap(18, 18, 18)
                .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCuisine.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), null));

        jLabelCuisine.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelCuisine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/countertops_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabelCuisine.setText("Tipo de cocina");
        jLabelCuisine.setToolTipText("Tipo de cocina");

        jButtonBuffet.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuffet.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonBuffet.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuffet.setText("Buffet");
        jButtonBuffet.setToolTipText("Botón Buffet");
        jButtonBuffet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBuffet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuffetActionPerformed(evt);
            }
        });

        jButtonCard.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCard.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonCard.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCard.setText("Carta");
        jButtonCard.setToolTipText("Botón Carta");
        jButtonCard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonChef.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChef.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonChef.setForeground(new java.awt.Color(0, 0, 0));
        jButtonChef.setText("Chef");
        jButtonChef.setToolTipText("Botón Chef");
        jButtonChef.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonOwnChoose.setBackground(new java.awt.Color(78, 79, 86));
        jButtonOwnChoose.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonOwnChoose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOwnChoose.setText("Ninguna preferencia");
        jButtonOwnChoose.setToolTipText("Botón Ninguna preferencia");
        jButtonOwnChoose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonOwnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOwnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCuisineLayout = new javax.swing.GroupLayout(jPanelCuisine);
        jPanelCuisine.setLayout(jPanelCuisineLayout);
        jPanelCuisineLayout.setHorizontalGroup(
            jPanelCuisineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuisineLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCuisineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOwnChoose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCuisineLayout.createSequentialGroup()
                        .addComponent(jButtonBuffet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonCard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonChef, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(jPanelCuisineLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabelCuisine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        jPanelCuisineLayout.setVerticalGroup(
            jPanelCuisineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuisineLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelCuisine)
                .addGap(17, 17, 17)
                .addGroup(jPanelCuisineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuffet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOwnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelEvent.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), null));

        jLabelEvent.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tema2SalonHabana/img/weekend_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabelEvent.setText("Tipo de evento");
        jLabelEvent.setToolTipText("Tipo de evento");

        jButtonFeast.setBackground(new java.awt.Color(78, 79, 86));
        jButtonFeast.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonFeast.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFeast.setText("Banquete");
        jButtonFeast.setToolTipText("Botón banquete");
        jButtonFeast.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonFeast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeastActionPerformed(evt);
            }
        });

        jButtonDayWork.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDayWork.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonDayWork.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDayWork.setText("Jornada");
        jButtonDayWork.setToolTipText("Botón jornada");
        jButtonDayWork.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCongress.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCongress.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonCongress.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCongress.setText("Congreso");
        jButtonCongress.setToolTipText("Botón congreso");
        jButtonCongress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCongress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCongress.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelRoom.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelRoom.setText("¿Habitaciones?");

        jButtonRoomNo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRoomNo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonRoomNo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRoomNo.setText("No");
        jButtonRoomNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRoomNo.setEnabled(false);
        jButtonRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomNoActionPerformed(evt);
            }
        });

        jButtonRoomYes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRoomYes.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonRoomYes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRoomYes.setText("Sí");
        jButtonRoomYes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRoomYes.setEnabled(false);

        javax.swing.GroupLayout jPanelRoomLayout = new javax.swing.GroupLayout(jPanelRoom);
        jPanelRoom.setLayout(jPanelRoomLayout);
        jPanelRoomLayout.setHorizontalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRoomLayout.createSequentialGroup()
                        .addComponent(jButtonRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRoomYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanelRoomLayout.createSequentialGroup()
                        .addComponent(jLabelRoom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelRoomLayout.setVerticalGroup(
            jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomLayout.createSequentialGroup()
                .addComponent(jLabelRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoomYes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelRoomDays.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelRoomDays.setText("¿Cuántos días?");

        jSpinnerRoomDays.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jSpinnerRoomDays.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerRoomDays.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSpinnerRoomDays.setEnabled(false);

        javax.swing.GroupLayout jPanelRoomsDaysLayout = new javax.swing.GroupLayout(jPanelRoomsDays);
        jPanelRoomsDays.setLayout(jPanelRoomsDaysLayout);
        jPanelRoomsDaysLayout.setHorizontalGroup(
            jPanelRoomsDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomsDaysLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRoomsDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRoomDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerRoomDays))
                .addContainerGap())
        );
        jPanelRoomsDaysLayout.setVerticalGroup(
            jPanelRoomsDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomsDaysLayout.createSequentialGroup()
                .addComponent(jLabelRoomDays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerRoomDays, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEventLayout = new javax.swing.GroupLayout(jPanelEvent);
        jPanelEvent.setLayout(jPanelEventLayout);
        jPanelEventLayout.setHorizontalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelEventLayout.createSequentialGroup()
                        .addComponent(jButtonFeast, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDayWork, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCongress, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEventLayout.createSequentialGroup()
                        .addComponent(jPanelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRoomsDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabelEvent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEventLayout.setVerticalGroup(
            jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEvent)
                .addGap(18, 18, 18)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFeast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDayWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCongress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRoomsDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelHallTypeLayout = new javax.swing.GroupLayout(jPanelHallType);
        jPanelHallType.setLayout(jPanelHallTypeLayout);
        jPanelHallTypeLayout.setHorizontalGroup(
            jPanelHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCuisine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHallTypeLayout.setVerticalGroup(
            jPanelHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHallTypeLayout.createSequentialGroup()
                .addComponent(jPanelCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelExtraHallDatesLayout = new javax.swing.GroupLayout(jPanelExtraHallDates);
        jPanelExtraHallDates.setLayout(jPanelExtraHallDatesLayout);
        jPanelExtraHallDatesLayout.setHorizontalGroup(
            jPanelExtraHallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraHallDatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHallType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelExtraHallDatesLayout.setVerticalGroup(
            jPanelExtraHallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtraHallDatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExtraHallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHallType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSection2_HallDatesLayout = new javax.swing.GroupLayout(jPanelSection2_HallDates);
        jPanelSection2_HallDates.setLayout(jPanelSection2_HallDatesLayout);
        jPanelSection2_HallDatesLayout.setHorizontalGroup(
            jPanelSection2_HallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection2_HallDatesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelSection2_HallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelExtraHallDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNumberPersons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSection2_HallDatesLayout.setVerticalGroup(
            jPanelSection2_HallDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSection2_HallDatesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelNumberPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelExtraHallDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jButtonReserve.setBackground(new java.awt.Color(10, 68, 142));
        jButtonReserve.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jButtonReserve.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReserve.setText("Reservar");
        jButtonReserve.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSection1_ClientDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSection2_HallDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSection1_ClientDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSection2_HallDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButtonReserve.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNumberPersonsOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberPersonsOneActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonNumberPersonsOneActionPerformed

    private void jCheckBoxNumberPersonsOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNumberPersonsOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNumberPersonsOtherActionPerformed

    private void jButtonNumberPersonsEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberPersonsEightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNumberPersonsEightActionPerformed

    private void jButtonBuffetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuffetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuffetActionPerformed

    private void jButtonOwnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOwnChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOwnChooseActionPerformed

    private void jTextField1_2_ClientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_2_ClientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_2_ClientPhoneActionPerformed

    private void jTextField1_1_ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_1_ClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_1_ClientNameActionPerformed

    private void jButtonFeastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeastActionPerformed

    private void jButtonRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRoomNoActionPerformed

    private void jButtonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveActionPerformed
        controlDatesCorrect = true;

        if (jTextField1_1_ClientName.getForeground().equals(Color.gray)) {
            assignPaddingBorder(jTextField1_1_ClientName, RED);
            controlDatesCorrect = false;
        }

        if (jTextField1_2_ClientPhone.getForeground().equals(Color.gray)) {
            assignPaddingBorder(jTextField1_2_ClientPhone, RED);
            controlDatesCorrect = false;
        }

        if (selectedDate == null) {
            jLabelDateChoosen.setForeground(RED);
            controlDatesCorrect = false;
        }

        if (controlDatesCorrect) {
            name = jTextField1_1_ClientName.getText().toString();
            phone = jTextField1_2_ClientPhone.getText().toString();

            reserve = new Reserve(name, phone, numPersons, selectedDate, cousine, event);
            salonHabana.aniadirReserva(reserve);

            dispose();
        }
    }//GEN-LAST:event_jButtonReserveActionPerformed

    private void initComponentsPersonalDates() {

        assignPlaceholderFocusListener(jTextField1_1_ClientName, "Escriba su nombre");
        assignPlaceholderFocusListener(jTextField1_2_ClientPhone, "Escriba su teléfono");

        assignPaddingBorder(jTextField1_1_ClientName, BORDER_BLACK_SOFT);
        assignPaddingBorder(jTextField1_2_ClientPhone, BORDER_BLACK_SOFT);

    }

    private static void assignPaddingBorder(JTextField textField, Color color) {
        textField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(color),
                BorderFactory.createEmptyBorder(2, 5, 0, 5)
        ));
    }

    private static void assignPlaceholderFocusListener(JTextField textField, String placeholder) {
        textField.setText(placeholder);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.black);
                    textField.setBackground(Color.white);
                    assignPaddingBorder(textField, BORDER_BLACK_SOFT);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.gray);

                }
            }
        });

    }

    private static void assignHoverButton(JButton button) {
        Color backgroundColorButton = button.getBackground();

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBorder(
                        BorderFactory.createEtchedBorder(Color.GRAY, null)
                );
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBorder(
                        BorderFactory.createEtchedBorder(null, null)
                );
            }
        });

    }

    private void initComponentsCalendar() {
        selectedDate = null;

        // Obtener la fecha actual
        Calendar calendar = Calendar.getInstance();

        // Incrementar la fecha actual en un día
        calendar.add(Calendar.DAY_OF_MONTH, 1);

        // Obtener la fecha mínima como Date
        Date minDate = calendar.getTime();
        jCalendarDate.setMinSelectableDate(minDate);

        // Ocultar los nombres de los días de la semana
        jCalendarDate.setWeekOfYearVisible(false);

        // Obtener el año actual
        int yearActual = Calendar.getInstance().get(Calendar.YEAR);

        // Acceder al JYearChooser dentro del JDateChooser
        JYearChooser yearChooser = jCalendarDate.getYearChooser();

        // Establecer el año mínimo en el JYearChooser
        yearChooser.setMinimum(yearActual);

        jCalendarDate.addPropertyChangeListener("calendar", (PropertyChangeEvent evt) -> {
            if ("calendar".equals(evt.getPropertyName())) {
                // Obtén el valor del nuevo calendario seleccionado
                GregorianCalendar selectedCalendar = (GregorianCalendar) evt.getNewValue();

                // Comprueba si la fecha seleccionada es posterior a la fecha actual
                if (selectedCalendar.getTime().after(new Date())) {
                    // Convierte el calendario a un objeto Date
                    selectedDate = selectedCalendar.getTime();

                    // Crea un formato de fecha personalizado
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

                    // Formatea la fecha como una cadena de texto
                    String formattedDate = dateFormat.format(selectedDate);

                    // Si es posterior, muestra la fecha en un JLabel y cambia el color a azul
                    jLabelDateChoosen.setText(formattedDate);
                    jLabelDateChoosen.setForeground(Color.BLUE); // Cambia el color del texto a azul
                }
            }
        });

    }

    private void initComponentNumberPersons() {
        // Inicializa las variables de cantidad de personas
        numPersons = "2";

        // Define un arreglo de botones
        JButton[] listButtons = {
            jButtonNumberPersonsOne,
            jButtonNumberPersonsTwo,
            jButtonNumberPersonsThree,
            jButtonNumberPersonsFour,
            jButtonNumberPersonsFive,
            jButtonNumberPersonsSix,
            jButtonNumberPersonsSeven,
            jButtonNumberPersonsEight};

        // Deshabilita inicialmente el spinner
        jSpinnerNumberPersonsOther.setEnabled(false);

        // ActionListener común para todos los botones
        ActionListener buttonClickListener = (ActionEvent e) -> {
            // Reinicia la selección del checkBox de otra cantidad de personas y deshabilita el spinner
            jCheckBoxNumberPersonsOther.setSelected(false);
            jSpinnerNumberPersonsOther.setEnabled(false);

            // Obtiene el botón seleccionado
            JButton selectedButton = (JButton) e.getSource();
            numPersons = selectedButton.getText();

            // Restaura el aspecto de todos los botones
            for (JButton button : listButtons) {
                button.setBackground(WHITE);
                button.setForeground(BLACK);
            }

            // Aplica el aspecto seleccionado al botón actual
            selectedButton.setBackground(BACKGROUND_BLACK_SOFT);
            selectedButton.setForeground(WHITE);
        };

        // Agregar el ActionListener común a los botones
        for (JButton button : listButtons) {
            button.addActionListener(buttonClickListener);
            assignHoverButton(button);
        }

        // ChangeListener común para jCheckBox y jSpinner
        ChangeListener checkBoxSpinnerChangeListener = (ChangeEvent e) -> {
            // Verifica si la casilla de verificación está seleccionada
            boolean checkBoxSelected = jCheckBoxNumberPersonsOther.isSelected();
            jSpinnerNumberPersonsOther.setEnabled(checkBoxSelected);

            // Actualiza la cantidad de personas
            numPersons = checkBoxSelected
                    ? jSpinnerNumberPersonsOther.getValue().toString()
                    : "";
        };

        // Agregar el ChangeListener común a jCheckBox y jSpinner
        jCheckBoxNumberPersonsOther.addChangeListener(checkBoxSpinnerChangeListener);
        jSpinnerNumberPersonsOther.addChangeListener(checkBoxSpinnerChangeListener);

        // ActionListener para la casilla de verificación del checkBox de otra cantidad de personas
        jCheckBoxNumberPersonsOther.addActionListener((ActionEvent e) -> {
            // Restaura el aspecto de todos los botones
            for (var button : listButtons) {
                button.setBackground(WHITE);
                button.setForeground(BLACK);
            }

            // Actualiza la cantidad de personas en función de la casilla de verificación
            if (jCheckBoxNumberPersonsOther.isSelected()) {
                numPersons = jSpinnerNumberPersonsOther.getValue().toString();
            } else {
                numPersons = "";
            }
        });
    }

    private void initComponentTypeCuisine() {
        cousine = "Ninguna preferencia";

        // Define un arreglo de botones
        JButton[] listButtons = {
            jButtonBuffet,
            jButtonCard,
            jButtonChef,
            jButtonOwnChoose
        };

        // ActionListener común para todos los botones
        ActionListener buttonClickListener = (ActionEvent e) -> {
            // Obtiene el botón seleccionado
            JButton selectedButton = (JButton) e.getSource();
            cousine = selectedButton.getText();

            // Restaura el aspecto de todos los botones
            for (JButton button : listButtons) {
                button.setBackground(WHITE);
                button.setForeground(BLACK);
            }

            // Aplica el aspecto seleccionado al botón actual
            selectedButton.setBackground(BACKGROUND_BLACK_SOFT);
            selectedButton.setForeground(WHITE);
        };

        // Agregar el ActionListener común a los botones
        for (JButton button : listButtons) {
            button.addActionListener(buttonClickListener);
            assignHoverButton(button);
        }

    }

    private void initComponentTypeEvent() {
        event = "Banquete";

        // Define un arreglo de botones
        JButton[] listButtons = {
            jButtonFeast,
            jButtonDayWork,
            jButtonCongress
        };

        // ActionListener común para todos los botones
        ActionListener buttonClickListener = (ActionEvent e) -> {
            // Obtiene el botón seleccionado
            JButton selectedButton = (JButton) e.getSource();
            event = selectedButton.getText();

            // Restaura el aspecto de todos los botones
            for (JButton button : listButtons) {
                button.setBackground(WHITE);
                button.setForeground(BLACK);

                jSpinnerRoomDays.setEnabled(false);
            }

            // Aplica el aspecto seleccionado al botón actual
            selectedButton.setBackground(BACKGROUND_BLACK_SOFT);
            selectedButton.setForeground(WHITE);

            if (event.equals("Congreso")) {
                event = "Congreso (0 días)";
                jButtonRoomNo.setEnabled(true);
                jButtonRoomYes.setEnabled(true);

                jButtonRoomNo.setBackground(BACKGROUND_BLACK_SOFT);
                jButtonRoomNo.setForeground(WHITE);

                jButtonRoomYes.setBackground(WHITE);
                jButtonRoomYes.setForeground(BLACK);
            } else {
                jButtonRoomNo.setEnabled(false);
                jButtonRoomYes.setEnabled(false);

                jButtonRoomNo.setBackground(WHITE);
                jButtonRoomNo.setForeground(BLACK);

                jButtonRoomYes.setBackground(WHITE);
                jButtonRoomYes.setForeground(BLACK);
            }
        };

        JButton[] listButtonsNoYes = {
            jButtonRoomNo,
            jButtonRoomYes
        };

        ActionListener buttonNoYesClickListener = (ActionEvent e) -> {
            // Obtiene el botón seleccionado
            JButton selectedButton = (JButton) e.getSource();

            // Restaura el aspecto de todos los botones
            for (JButton button : listButtonsNoYes) {
                button.setBackground(WHITE);
                button.setForeground(BLACK);
            }

            // Aplica el aspecto seleccionado al botón actual
            selectedButton.setBackground(BACKGROUND_BLACK_SOFT);
            selectedButton.setForeground(WHITE);

            if (selectedButton.getText().equals("Sí")) {
                jSpinnerRoomDays.setEnabled(true);
                
                event = "Congreso (" + jSpinnerRoomDays.getValue().toString() + " días)";
            } else {
                jSpinnerRoomDays.setEnabled(false);
                event = "Congreso (0 días)";
            }
            jSpinnerRoomDays.setEnabled(
                    selectedButton.getText().equals("Sí")
            );
        };
        
        jSpinnerRoomDays.addChangeListener((ChangeEvent e) -> {
            event = "Congreso (" + jSpinnerRoomDays.getValue().toString() + " días)";
        });

        // Agregar el ActionListener común a los botones
        for (JButton button : listButtons) {
            button.addActionListener(buttonClickListener);
            assignHoverButton(button);
        }

        for (JButton button : listButtonsNoYes) {
            button.addActionListener(buttonNoYesClickListener);
            assignHoverButton(button);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReservaSalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReservaSalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReservaSalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReservaSalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionReservaSalonHabana dialog = new GestionReservaSalonHabana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuffet;
    private javax.swing.JButton jButtonCard;
    private javax.swing.JButton jButtonChef;
    private javax.swing.JButton jButtonCongress;
    private javax.swing.JButton jButtonDayWork;
    private javax.swing.JButton jButtonFeast;
    private javax.swing.JButton jButtonNumberPersonsEight;
    private javax.swing.JButton jButtonNumberPersonsFive;
    private javax.swing.JButton jButtonNumberPersonsFour;
    private javax.swing.JButton jButtonNumberPersonsOne;
    private javax.swing.JButton jButtonNumberPersonsSeven;
    private javax.swing.JButton jButtonNumberPersonsSix;
    private javax.swing.JButton jButtonNumberPersonsThree;
    private javax.swing.JButton jButtonNumberPersonsTwo;
    private javax.swing.JButton jButtonOwnChoose;
    private javax.swing.JButton jButtonReserve;
    private javax.swing.JButton jButtonRoomNo;
    private javax.swing.JButton jButtonRoomYes;
    private com.toedter.calendar.JCalendar jCalendarDate;
    private javax.swing.JCheckBox jCheckBoxNumberPersonsOther;
    private javax.swing.JLabel jLabel1_1_ClientName;
    private javax.swing.JLabel jLabel1_2_ClientPhone;
    private javax.swing.JLabel jLabelCuisine;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDateChoosen;
    private javax.swing.JLabel jLabelEvent;
    private javax.swing.JLabel jLabelNumberPersons;
    private javax.swing.JLabel jLabelRoom;
    private javax.swing.JLabel jLabelRoomDays;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelClientDatesBackground;
    private javax.swing.JPanel jPanelClientName;
    private javax.swing.JPanel jPanelClientPhone;
    private javax.swing.JPanel jPanelCuisine;
    private javax.swing.JPanel jPanelDate;
    private javax.swing.JPanel jPanelEvent;
    private javax.swing.JPanel jPanelExtraHallDates;
    private javax.swing.JPanel jPanelHallType;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNumberPersons;
    private javax.swing.JPanel jPanelNumberPersonsChoose;
    private javax.swing.JPanel jPanelRoom;
    private javax.swing.JPanel jPanelRoomsDays;
    private javax.swing.JPanel jPanelSection1_ClientDates;
    private javax.swing.JPanel jPanelSection2_HallDates;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JSpinner jSpinnerNumberPersonsOther;
    private javax.swing.JSpinner jSpinnerRoomDays;
    private javax.swing.JTextField jTextField1_1_ClientName;
    private javax.swing.JTextField jTextField1_2_ClientPhone;
    // End of variables declaration//GEN-END:variables

    private static class FocusAdapterImpl extends FocusAdapter {

        public FocusAdapterImpl() {
        }
    }
}
