/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tema2GestorClientes.gui;

import Tema2GestorClientes.dto.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jordan
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        inicializarTabla();
    }

    private void inicializarTabla() {
        var dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{
            "Nombre",
            "Apellidos",
            "Fecha Alta",
            "Provincia"
        });
        jTablePrincipalCliente.setModel(dtm);
    }
    
    public void aniadirCliente(Cliente cliente) {
        var dtm = (DefaultTableModel) jTablePrincipalCliente.getModel();
        dtm.addRow(cliente.toArrayStrings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalCliente = new javax.swing.JPanel();
        jScrollPanePrincipalCliente = new javax.swing.JScrollPane();
        jTablePrincipalCliente = new javax.swing.JTable();
        jMenuBarPantallaPrincipal = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemClientes1_Alta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor clientes");

        jPanelPrincipalCliente.setBackground(new java.awt.Color(0, 0, 0));

        jTablePrincipalCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePrincipalCliente.setViewportView(jTablePrincipalCliente);

        javax.swing.GroupLayout jPanelPrincipalClienteLayout = new javax.swing.GroupLayout(jPanelPrincipalCliente);
        jPanelPrincipalCliente.setLayout(jPanelPrincipalClienteLayout);
        jPanelPrincipalClienteLayout.setHorizontalGroup(
            jPanelPrincipalClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPanePrincipalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanelPrincipalClienteLayout.setVerticalGroup(
            jPanelPrincipalClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePrincipalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenuClientes.setText("Clientes");

        jMenuItemClientes1_Alta.setText("Altas");
        jMenuItemClientes1_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientes1_AltaActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemClientes1_Alta);

        jMenuBarPantallaPrincipal.add(jMenuClientes);

        setJMenuBar(jMenuBarPantallaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClientes1_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientes1_AltaActionPerformed
        DialogoAlta dialogoAlta = new DialogoAlta(this, true);
        dialogoAlta.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientes1_AltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarPantallaPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuItemClientes1_Alta;
    private javax.swing.JPanel jPanelPrincipalCliente;
    private javax.swing.JScrollPane jScrollPanePrincipalCliente;
    private javax.swing.JTable jTablePrincipalCliente;
    // End of variables declaration//GEN-END:variables
}
